# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run Bazel tests
on: [push, pull_request]

jobs:
  emacs-stable:
    name: Latest stable GNU Emacs release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Run Bazel tests
        run: bazel test --test_output=errors -- //...

  emacs-versions:
    name: All supported GNU Emacs versions
    strategy:
      matrix:
        version: [27.1, 27.2]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Run Bazel tests
        run: |
          bazel test \
            --test_output=errors \
            --extra_toolchains=@phst_rules_elisp//elisp:emacs_${{matrix.version}}_toolchain \
            -- //...

  bazel-versions:
    name: All supported Bazel versions
    strategy:
      matrix:
        version: [3.4.0, 3.4.1, 3.5.0, 3.5.1, 3.6.0, 3.7.0, 3.7.1, 3.7.2,
                  4.0.0, 4.1.0, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Run Bazel tests
        run: bazel test --test_output=errors -- //...
        env:
          USE_BAZEL_VERSION: ${{matrix.version}}
